[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8F5"
textColor = "#333333"

[global]
developmentMode = false
